import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import { ClientProvider, ReactQueryClientProvider } from "@/store/clientProvider";
import FeedbackMessage from "@/ReusableComp/feedBackMessage";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  mx-auto `}
      >
        <ClientProvider>
          <ReactQueryClientProvider>
            <NavBar />
            {children}
            <FeedbackMessage />
          </ReactQueryClientProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
