import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navbar";
import ClientProvider from "@/store/clientProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  mx-auto `}
      >
        <ClientProvider>
          <NavBar />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
